# Generated by Django 3.1.2 on 2020-10-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField()),
                ('unit_1', models.CharField(max_length=3)),
                ('unit_2', models.CharField(max_length=3)),
            ],
        ),
    ]
